# Copyright 2026 University of Sydney
# Licensed under the Apache License, Version 2.0.
#
# GOLD-TOKEN DATA COLLECTION for the AR-head training set (pure DMax, NO drafter).
#
# For each prompt we run the SAME faithful DMax heavy-only block decode used by the layer-readout probe
# (decode_and_maybe_probe with gold_block_fn=None) at the inference threshold, and store the model's own
# committed answer as the training target ("self-gold"). No ground-truth answers are used -- the AR head is
# a shortcut to the model's OWN output, so the model's decode IS the label.
#
# Source: nvidia/Nemotron-Post-Training-Dataset-v2, config "SFT", split "math" (239,467 prompts). Only the
# user question is used; the response is generated by our DMax model (gen_length default 512).
#
# ---------------------------------------------------------------------------------------------------------
# REPRODUCIBLE, EXTENSIBLE SAMPLING (the whole point of the seeding design)
# ---------------------------------------------------------------------------------------------------------
#   * One GLOBAL permutation of all N rows is fixed by --seed (numpy default_rng). This defines a stable
#     mapping rank -> dataset_index that NEVER changes for a given seed.
#   * We collect a contiguous RANK range [--start, --end). So:
#         5k  set  =  --start 0    --end 5000
#         50k set  =  --start 0    --end 50000        (ranks 0..4999 are BYTE-IDENTICAL to the 5k set)
#     To EXTEND 5k -> 50k you simply run  --start 5000 --end 50000  : the first 5k are never recomputed and
#     never change; you only pay for the new 45k. Rank r always resolves to the same prompt.
#   * SHARDING for multi-GPU: within [start,end), shard s of P takes ranks where (rank-start) % P == s
#     (strided -> balanced). Each shard writes its own JSONL; merge = concat + sort by "rank".
#   * Per-example DECODE seed is derived from the global rank (torch.manual_seed(seed_mix(rank))), so a row's
#     gold is identical no matter which shard / GPU / order produced it (decode is deterministic anyway; this
#     makes it robust to any future sampling in the decode path).
#   * RESUME: on restart we read the shard's existing JSONL and skip ranks already written (idempotent).
#
# Each output line is fully self-contained (no tokenizer/template needed at train time):
#   {"rank", "ds_index", "prompt", "prompt_ids", "gold_ids", "prompt_len", "eos_cut", "resp_len",
#    "gen_length", "block_length", "gold_threshold", "model", "seed"}
#   full sequence = prompt_ids + gold_ids ;  gold_ids = response tokens up to (not incl.) the gold EOS cut.
#
# Runbook (GPU box, merged DMax checkpoint; the dataset may need `huggingface-cli login`):
#   # 0) cheap validation of field extraction WITHOUT loading the model:
#   python collect_gold_data.py --dry_run --start 0 --end 3
#   # 1) first trial (5k):
#   python collect_gold_data.py --model_path ../../DMax-Math-16B-moe-merge \
#       --out_dir runs/gold_nemotron_math --start 0 --end 5000 --gen_length 512
#   # 2) later extend to 50k (first 5k untouched):
#   python collect_gold_data.py --model_path ../../DMax-Math-16B-moe-merge \
#       --out_dir runs/gold_nemotron_math --start 5000 --end 50000 --gen_length 512
#   # multi-GPU for a range (run one per GPU):
#   CUDA_VISIBLE_DEVICES=0 python collect_gold_data.py ... --start 0 --end 50000 --num_shards 4 --shard_id 0
#   CUDA_VISIBLE_DEVICES=1 python collect_gold_data.py ... --start 0 --end 50000 --num_shards 4 --shard_id 1  ...

import argparse
import json
import os
import sys
import time

import numpy as np
import torch

_HERE = os.path.dirname(os.path.abspath(__file__))
if _HERE not in sys.path:
    sys.path.insert(0, _HERE)

# Reuse the probe's byte-for-byte DMax decode + fused-MoE loader (keeps gold identical to the probe).
from probe_layer_readout import load_fused, decode_and_maybe_probe  # noqa: E402

DATASET = "nvidia/Nemotron-Post-Training-Dataset-v2"
CONFIG = "default"   # the repo currently exposes only the 'default' config
SPLIT = "math"       # may be a real HF split OR a 'category' value inside a base split (auto-handled)
# candidate field layouts to auto-detect (Nemotron uses a chat-style list; we fall back to plain strings)
_MSG_FIELDS = ["messages", "input", "conversations", "conversation", "prompt"]
_STR_FIELDS = ["question", "problem", "prompt", "input", "query", "text"]


def seed_mix(seed, rank):
    """Stable 63-bit per-example seed from (global seed, global rank). Order/shard independent."""
    return (int(seed) * 1_000_003 + int(rank) * 2_654_435_761) % (2 ** 63 - 1)


def extract_question(row, prompt_field=None, prompt_role="user"):
    """Return the user question string from one dataset row, robust to schema. If --prompt_field is given it
    wins. Otherwise: (1) a chat-style list of {role, content} -> content of the LAST message with role==user
    (or the first if none tagged); (2) a plain string field. Raises with the row keys if nothing matches."""
    def from_msgs(msgs):
        if isinstance(msgs, list) and msgs and isinstance(msgs[0], dict):
            users = [m.get("content", "") for m in msgs if m.get("role") == prompt_role]
            if users:
                return users[-1]
            return msgs[0].get("content", "")
        if isinstance(msgs, str):
            return msgs
        return None

    if prompt_field is not None:
        v = row[prompt_field]
        q = from_msgs(v) if not isinstance(v, str) else v
        if q:
            return q
        raise ValueError(f"--prompt_field={prompt_field!r} present but empty/unparsable; value={v!r}")

    for f in _MSG_FIELDS:
        if f in row:
            q = from_msgs(row[f])
            if q:
                return q
    for f in _STR_FIELDS:
        if f in row and isinstance(row[f], str) and row[f].strip():
            return row[f]
    raise ValueError(f"Could not find a question field. Row keys: {list(row.keys())}. "
                     f"Pass --prompt_field explicitly.")


def resolve_dataset(dataset, config, split, base_split=None, category_field=None):
    """Load the target rows, robust to the two possible layouts:
       (A) 'math' is a real HF split under the config -> load it directly;
       (B) 'math' is a value of a 'category'-like column inside one base split -> load base + filter.
    Returns (ds, meta). Auto-falls-back config -> 'default'/first if the requested one is absent."""
    from datasets import load_dataset, get_dataset_config_names, get_dataset_split_names
    configs = get_dataset_config_names(dataset)
    cfg = config if config in configs else ("default" if "default" in configs else configs[0])
    if cfg != config:
        print(f"[collect] config {config!r} not in {configs}; using {cfg!r}")
    splits = get_dataset_split_names(dataset, cfg)
    print(f"[collect] config={cfg!r} available splits={splits}")
    if split in splits:                                            # layout (A)
        ds = load_dataset(dataset, cfg, split=split)
        return ds, dict(config=cfg, split=split, filtered=False)
    base = base_split or ("train" if "train" in splits else splits[0])   # layout (B)
    print(f"[collect] {split!r} is not a split; loading base split {base!r} then filtering by category=={split!r}")
    ds = load_dataset(dataset, cfg, split=base)
    cols = list(ds.features.keys())
    catf = category_field or next(
        (c for c in ("category", "categories", "domain", "subset", "source", "task", "split") if c in cols), None)
    if catf is None:
        raise ValueError(f"No category-like column found to filter by (columns={cols}); "
                         f"pass --category_field, or set --split to a real split from {splits}")
    ds = ds.filter(lambda r: r[catf] == split)
    print(f"[collect] filtered {catf}=={split!r} -> {len(ds)} rows")
    return ds, dict(config=cfg, split=base, filtered=True, category_field=catf)


def load_done_ranks(path):
    """Ranks already present in a shard's JSONL (for --resume). Tolerates a truncated last line."""
    done = set()
    if not os.path.exists(path):
        return done
    with open(path) as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            try:
                done.add(int(json.loads(line)["rank"]))
            except Exception:
                continue  # partial/corrupt trailing line -> ignore
    return done


def main():
    p = argparse.ArgumentParser(description="Collect DMax self-gold tokens for AR-head training")
    p.add_argument("--model_path", default=None, help="MERGED DMax checkpoint (not needed for --dry_run)")
    p.add_argument("--tokenizer_path", default=None)
    p.add_argument("--out_dir", default="runs/gold_nemotron_math")
    p.add_argument("--dataset", default=DATASET)
    p.add_argument("--config", default=CONFIG)
    p.add_argument("--split", default=SPLIT)
    p.add_argument("--prompt_field", default=None, help="override auto-detect of the question field")
    p.add_argument("--prompt_role", default="user")
    p.add_argument("--base_split", default=None, help="(layout B) base split to load before category-filtering")
    p.add_argument("--category_field", default=None, help="(layout B) column to match against --split")
    # sampling / sharding
    p.add_argument("--seed", type=int, default=1234, help="fixes the GLOBAL rank->row permutation")
    p.add_argument("--start", type=int, default=0, help="first rank (inclusive)")
    p.add_argument("--end", type=int, default=5000, help="last rank (exclusive)")
    p.add_argument("--num_shards", type=int, default=1)
    p.add_argument("--shard_id", type=int, default=0)
    p.add_argument("--resume", action="store_true", help="skip ranks already in this shard's output")
    # decode
    p.add_argument("--gen_length", type=int, default=512)
    p.add_argument("--block_length", type=int, default=32)
    p.add_argument("--gold_threshold", type=float, default=0.5,
                   help="commit gate for the gold decode (0.5 = model's real inference output)")
    p.add_argument("--device", default="cuda")
    p.add_argument("--flush_every", type=int, default=20)
    p.add_argument("--dry_run", action="store_true",
                   help="load dataset, print schema + extracted questions for the range, DO NOT load model")
    args = p.parse_args()

    assert 0 <= args.shard_id < args.num_shards, "shard_id must be in [0, num_shards)"
    assert args.start < args.end, "need start < end"

    print(f"[collect] loading {args.dataset} [{args.config}/{args.split}] ...")
    ds, dsmeta = resolve_dataset(args.dataset, args.config, args.split, args.base_split, args.category_field)
    N = len(ds)
    print(f"[collect] {N} rows; features: {list(ds.features.keys())}  ({dsmeta})")
    if args.dry_run:                                              # show raw structure of the first row
        row0 = ds[0]
        print("[dry_run] first-row keys + truncated values:")
        for kk, vv in row0.items():
            print(f"    {kk}: {str(vv)[:160]!r}")

    # global, seed-fixed permutation: rank -> dataset index (immutable for a given --seed)
    perm = np.random.default_rng(args.seed).permutation(N)
    end = min(args.end, N)
    if args.end > N:
        print(f"[collect] WARN --end {args.end} > N {N}; clamped to {N}")

    # ranks this shard owns within [start, end): strided so P shards balance the range
    ranks = [r for r in range(args.start, end) if (r - args.start) % args.num_shards == args.shard_id]

    os.makedirs(args.out_dir, exist_ok=True)
    tag = "single" if args.num_shards == 1 else f"shard{args.shard_id:02d}of{args.num_shards:02d}"
    out_path = os.path.join(args.out_dir, f"gold.{tag}.jsonl")

    if args.dry_run:
        print(f"[dry_run] would write -> {out_path}; showing extraction for first up-to-5 ranks:")
        for r in ranks[:5]:
            row = ds[int(perm[r])]
            q = extract_question(row, args.prompt_field, args.prompt_role)
            print(f"  rank={r} ds_index={int(perm[r])} | Q[:160]={q[:160]!r}")
        print(f"[dry_run] this shard owns {len(ranks)} ranks in [{args.start},{end}). No model loaded. Done.")
        return

    done = load_done_ranks(out_path) if args.resume else set()
    todo = [r for r in ranks if r not in done]
    print(f"[collect] shard owns {len(ranks)} ranks; {len(done)} already done; {len(todo)} to do -> {out_path}")
    if not todo:
        print("[collect] nothing to do.")
        return

    device = torch.device(args.device)
    mp = os.path.abspath(args.model_path)
    from transformers import AutoTokenizer
    tok = AutoTokenizer.from_pretrained(os.path.abspath(args.tokenizer_path or mp), trust_remote_code=True)
    model = load_fused(mp, device)
    embed = model.get_input_embeddings()
    lm_head = model.get_output_embeddings()
    final_norm = model.model.norm
    V = int(model.config.vocab_size)
    model_name = os.path.basename(mp.rstrip("/"))
    print(f"[collect] model={model_name} vocab={V} gen={args.gen_length} block={args.block_length} "
          f"gold_thr={args.gold_threshold}")

    t0 = time.time()
    n_written = 0
    with open(out_path, "a") as fh:
        for j, r in enumerate(todo):
            ds_index = int(perm[r])
            row = ds[ds_index]
            try:
                q = extract_question(row, args.prompt_field, args.prompt_role)
            except ValueError as e:
                print(f"[collect] rank={r} skipped: {e}")
                continue

            torch.manual_seed(seed_mix(args.seed, r))  # order/shard-independent per-example determinism
            msgs = [{"role": "user", "content": q}]
            pid = tok.apply_chat_template(msgs, add_generation_prompt=True, tokenize=True,
                                          return_tensors="pt").to(device)
            P = pid.shape[1]

            gold_x, gold_eos = decode_and_maybe_probe(
                model, embed, lm_head, final_norm, pid, args.gen_length, args.block_length,
                args.gold_threshold, V, device, gold_block_fn=None, acc=None)

            resp = gold_x[P:gold_eos].tolist()
            rec = dict(rank=r, ds_index=ds_index, prompt=q, prompt_ids=pid[0].tolist(), gold_ids=resp,
                       prompt_len=P, eos_cut=int(gold_eos), resp_len=len(resp), gen_length=args.gen_length,
                       block_length=args.block_length, gold_threshold=args.gold_threshold,
                       model=model_name, seed=args.seed)
            fh.write(json.dumps(rec, ensure_ascii=False) + "\n")
            n_written += 1
            if (j + 1) % args.flush_every == 0:
                fh.flush()
                os.fsync(fh.fileno())
            if j < 3 or (j + 1) % 50 == 0:
                rate = (j + 1) / max(time.time() - t0, 1e-6)
                eta = (len(todo) - j - 1) / max(rate, 1e-6)
                print(f"[{j+1}/{len(todo)}] rank={r} P={P} resp_len={len(resp)} eos_cut={gold_eos} "
                      f"{rate:.2f} ex/s ETA={eta/60:.1f}m")

    print(f"[collect] wrote {n_written} records in {time.time()-t0:.0f}s -> {out_path}")


if __name__ == "__main__":
    main()
